#!/bin/bash
rm instala-ptgc
mkdir  ~/.local/ptgc
cd ~/.local/ptgc
wget https://github.com/flavio7co/portugol-c/blob/master/compila.c
mkdir  ~/.local/share
mkdir  ~/.local/share/gtksourceview-3.0
mkdir  ~/.local/share/gtksourceview-2.0
mkdir  ~/.local/share/gtksourceview-3.0/language-specs
mkdir  ~/.local/share/gtksourceview-2.0/language-specs
cd  ~/.local/share/gtksourceview-3.0/language-specs/
wget https://github.com/flavio7co/portugol-c/blob/master/ptgc.lang
cp ptgc.lang ~/.local/share/gtksourceview-2.0/language-specs
mkdir $HOME/portugol
cc ~/.local/ptgc/compila.c -o $HOME/portugol/compila
rm ~/.local/ptgc/compila.c
cd $HOME/portugol/
./compila preparar
gedit algoritmo.alg
